### ISSUE TITLE
Keylogs

### ISSUE THREAD

**Issue by Patrickology** [mvrozanti/RAT-via-Telegram#10]
Hi,

sent the /keylogs command and the bot spits out a .txt file but there isn't much to read..

![image](https://cloud.githubusercontent.com/assets/28252390/26656122/1413d282-465e-11e7-9228-5b5f356ac0bd.png)

**Comment by mvrozanti** [comment]
keylogs.txt is now .user
check [commit e188567a0d97d660017ebde8e43a4df021cba001](https://github.com/mvrozanti/RAT-via-Telegram/commit/e188567a0d97d660017ebde8e43a4df021cba001)
