### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by Dviros** [mvrozanti/RAT-via-Telegram#14]
Hey dude, I've added new features:
1. Migrated to the new telepot messageloop function (old one was deprecated).
2. Shutdown and reboot
3. NSLOOKUP
4. DNS_Cache

https://github.com/Dviros/RAT-via-Telegram/commit/a23fa15f7ee9de5de4ca8bdf41507a7020dabba7

Also, can you please add me as a contributer?
Thanks a lot!

**Comment by mvrozanti** [comment]
Adding soon. Except for NsLookup command which doesn't accept -ls argument on my machine.
