### ISSUE TITLE
For me freeze keyboard and mouse is not working.

### ISSUE THREAD

**Issue by PulkitSingh256** [mvrozanti/RAT-via-Telegram#20]
I tried a several commands which doesn't appeared to work.
For example telegram apps hangs when we send command /nslookup 
And freeze mouse keyboard doesn't works

**Comment by mvrozanti** [comment]
Can you post your system specifications? It's working fine here

**Comment by PulkitSingh256** [comment]
Core i3 6th gen 
8gb ram
Windows 10 Creators update 
I also tried on my father's laptop it didn't worked their also.

**Comment by mvrozanti** [comment]
Have you tried cloning the latest version? I think I fixed those. Do tell if it doesn't work.

**Comment by PulkitSingh256** [comment]
i will tell you tomorrow
