### ISSUE TITLE
/get_chrome not working

### ISSUE THREAD

**Issue by adastmins** [mvrozanti/RAT-via-Telegram#21]
callback(item)
  File "C:\1111\rat.py", line 600, in handle
    responses = split_string(4096, response)
  File "C:\1111\rat.py", line 184, in split_string
    for i in str(st):
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6628-6631:
 ordinal not in range(128)

**Comment by mvrozanti** [comment]
The problem in this case is that some non-unicode character is being appended to our responses_string. What's your target machine's default charset?

**Comment by kojibhy** [comment]
more troubles you will have when you compile with no console and pyinstaller
to solve all these problems you need to use this wrapper for subprocess call:

`def subprocess_args(include_stdout=True):

    if hasattr(subprocess, 'STARTUPINFO'):

        si = subprocess.STARTUPINFO()
        si.dwFlags |= subprocess.STARTF_USESHOWWINDOW

        env = os.environ
    else:
        si = None
        env = None

    if include_stdout:
        ret = {'stdout': subprocess.PIPE}
    else:
        ret = {}

    ret.update({'stdin': subprocess.PIPE,
                'stderr': subprocess.PIPE,
                'startupinfo': si,
                'env': env })
    return ret


s = subprocess.check_output('tasklist', **subprocess_args(False))
output = s.decode('utf-8', 'ignore')`

**Comment by mvrozanti** [comment]
@kojibhy 
Have you tested this? Pull requests are more than welcome at this point

**Comment by kojibhy** [comment]
yes, I use it all time with pyinstaller --noconsole

**Comment by Suburbanno** [comment]
How to solve? I'm a beginner at this, I tried using an old script using the path of my computer.
But it didn't work

![google](https://user-images.githubusercontent.com/13632826/35686883-859eb09a-0754-11e8-9aad-9dbcd0a6bfa7.PNG)

**Comment by PulkitSingh256** [comment]
This function don't work as of now and one issue has already opened on same topic

**Comment by mvrozanti** [comment]
@Suburbanno welcome. 

Most we can handle here are errors so if you can spew out as many as you can that would be great

**Comment by PulkitSingh256** [comment]
Login Data can be decrypted locally and then the credentials can be transferred.
I didn't looked at Nexor's Code yet but I saw a similar chrome password extractor. This trick should work

**Comment by Suburbanno** [comment]
@mvrozanti welcome again, good, it is not persistent, when turning on the computer, the process be active but the bot does not work, I have to open the. exe again

**Comment by Suburbanno** [comment]
@mvrozanti  end I'm loving tinkering with all this, please do not abandon the project, continue adding resources

**Comment by mvrozanti** [comment]
@Suburbanno have you got admin permissions on target machine?

**Comment by Suburbanno** [comment]
@mvrozanti vai ser em pt mesmo, tenho permissões admin sim, já que vc atualizou, vou fazer tudo do zero e dou o feedback.

**Comment by Suburbanno** [comment]
@mvrozanti bom, como antes, só alguns comandos funcionam, os demais param o bot.

**Comment by mvrozanti** [comment]
Win10?

**Comment by Suburbanno** [comment]
sim, estou usando o Windows 10 pro, como posso obter os logs?

**Comment by mvrozanti** [comment]
`%appdata%/Portal` probably.

**Comment by Suburbanno** [comment]
não consegui upar o arquivo aqui, segue no [pastebin](https://pastebin.com/4d8Dp1n2)
@mvrozanti  
![portal](https://user-images.githubusercontent.com/13632826/36076382-87b677aa-0f42-11e8-849f-87bac77590e2.PNG)
Bom, sobre o windows defender não posso te falar, ele é desativado aqui.

**Comment by Suburbanno** [comment]
@mvrozanti

**Comment by mvrozanti** [comment]
What we should be doing is append exception logs to a new file. But for the time's sake, try and run it in the shell wtih `python2`.

**Comment by Suburbanno** [comment]
@mvrozanti [pastebin](https://pastebin.com/1ymUCixR) só tenho o python2 instalado.
apaguei o arquivo de log antigo, rodei o script, executei os comandos que funcionavam e em seguida os que freezam o bot, gerando assim esse log.

**Comment by mvrozanti** [comment]
This is actually a separate issue than that of get_chrome so you should create a new one. I do not know why this is happening. I do know that you cannot run two instances of the same bot at the same time. Maybe this is related to the error?

Else I really don't know what to look for.

**Comment by Suburbanno** [comment]
@mvrozanti execute o comando /arp por exemplo, ele irá freezar o bot.

**Comment by mvrozanti** [comment]
Since `/get_chrome` works I'm closing this.
