### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by viviaja** [mvrozanti/RAT-via-Telegram#22]
Got these errors while executing RATattack.py on windows7

File "D:\HACK\RAT\Windows\RAT-via-Telegram-update\RATAttack.py", line 138
  print tofile
SyntaxError: Missing parentheses in call to 'print'

any idea?

**Comment by mvrozanti** [comment]
This is a Python 2.7 project, you're probably running on 3.x
