### ISSUE TITLE
hear not working 

### ISSUE THREAD

**Issue by X3eRo0** [mvrozanti/RAT-via-Telegram#23]
just buzzzzz and also whenever i play mouthlog.wav crashes telegram
i have to save it to music and then listen it so please help

**Comment by mvrozanti** [comment]
Sorry to read that

I've moved to Linux so I'm currently not entirely dedicated to this project, at least until I get my VM going and stuff. I'd say you could experiment with the input device selection (may be the wrong one).

Now as for mouthlog.wav crashing telegram, I don't have any proof of this but I'm pretty sure it's the damn WAV format/extension. Sending it in MP3 would be cheaper data-wise and faster

**Comment by JEAN17RUS** [comment]
Why don't use OGG instead of WAV?

**Comment by PulkitSingh256** [comment]
I was busy and I will fix this issue

**Comment by mvrozanti** [comment]
Is this still happening? I might get back to development soon, this would be a first

**Comment by PulkitSingh256** [comment]
Actually i didnt got it to work  my exams are going
