### ISSUE TITLE
Wrong line commented out in RATAttack.py at line 33: token = os.environ['RAT_TOKEN']

### ISSUE THREAD

**Issue by tylers86** [mvrozanti/RAT-via-Telegram#24]
Looks like the provided RATAttack.py script has the wrong line accidentally commented out. Looks like:

31 # REPLACE THE LINE BELOW WITH THE TOKEN OF THE BOT YOU GENERATED!
32 #token = 'nnnnnnnnn:lllllllllllllllllllllllllllllllllll'
33 token = os.environ['RAT_TOKEN'] 				# you can set your environment variable as well

Should be:

31 # REPLACE THE LINE BELOW WITH THE TOKEN OF THE BOT YOU GENERATED!
32 token = 'nnnnnnnnn:lllllllllllllllllllllllllllllllllll'
33 #token = os.environ['RAT_TOKEN'] 				# you can set your environment variable as well

**Comment by PulkitSingh256** [comment]
Yes you are right I have also fixed that in my forked rat via Telegram also made changes in the script and now the keyboard freezing and mouse freezing are working. Made compiling easy

**Comment by PulkitSingh256** [comment]
GitHub.com/PulkitSingh256

**Comment by mvrozanti** [comment]
That's actually what I tried to state in the comment. You *either* set an environment variable if you're going to be uploading to Github or you can hardcore the `numbers:letters` format in your source.

Nevertheless,
@PulkitSingh256 I'm glad there's  still some maintainance happening. Keep it up
