### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by boff64** [mvrozanti/RAT-via-Telegram#25]
The best thing you can make is Android rat support with webcam snaps, mic recording, download of images from devices memory, geolocate and mic streaming and keylogger.

**Comment by PulkitSingh256** [comment]
I was also thinking about it. But problem comes where Android does not uses python application to run it needs an APK file to run its contents.

**Comment by boff64** [comment]
Yea, I know that but if someone we can make a client who runs on Telegram but has support for apk, there is a lot of Android RAT open source tools, if we can find a good one and just add Telegram support to it or modify this.

**Comment by mvrozanti** [comment]
@boff64 @PulkitSingh256 is right. You're looking for metasploit payloads which can't use Telegram bots as C&C servers at the present moment. But an Android RAT is 100% possible with msfvenom utility.
