### ISSUE TITLE
Why is /self_destruct not working

### ISSUE THREAD

**Issue by PulkitSingh256** [mvrozanti/RAT-via-Telegram#27]
Why is freeze_keyboard
freeze_mouse doesn't respond
Is it because of this 
`
destroy = False
keyboardFrozen = False
mouseFrozen = False
curr_window = None
`

**Comment by mvrozanti** [comment]
No

**Comment by PulkitSingh256** [comment]
Can I ask what does .idea do?

**Comment by mvrozanti** [comment]
It was pycharm's preferences for the project. Removed, thank you for noting.
