### ISSUE TITLE
After a few minutes does not work anymore, even with the process running

### ISSUE THREAD

**Issue by Suburbanno** [mvrozanti/RAT-via-Telegram#28]
![no work](https://user-images.githubusercontent.com/13632826/35688758-0be4f25a-0759-11e8-90d0-f595b982c966.PNG)

**Comment by PulkitSingh256** [comment]
Don't run dns command that causes this

**Comment by Suburbanno** [comment]
oh, thanks

**Comment by Suburbanno** [comment]
only a few commands works =/
/arp also makes it stop working
