### ISSUE TITLE
Dont work download function

### ISSUE THREAD

**Issue by lybimiy86** [mvrozanti/RAT-via-Telegram#31]
When I use the download command, it always says that the file was not found, but the file is there.
1 attemp
`/download C:/test/1.bmp `
> Could not find 1.bmp

2 attemp
```
/cd c:\\
/cd test
/ls
```
> 1.bmp

`/download 1.bmp`
> Could not find 1.bmp

![2018-02-11_23-37-09](https://user-images.githubusercontent.com/26028702/36078250-1ad25ca6-0f85-11e8-930b-af9766038303.png)

**Comment by mvrozanti** [comment]
Have you tried actually opening it? Windows Explorer sometimes doesn't refresh image thumbnails and whatnot. 

Can you run the following in a powershell?
```
Get-Item ./1.bmp | Format-List
```
