### ISSUE TITLE
keylogs does not work correctly?

### ISSUE THREAD

**Issue by lybimiy86** [mvrozanti/RAT-via-Telegram#32]
when I send the command / keylogs, the .user file comes with the following content, there are a lot of such lines, there are no other data

> Admin Log: Feb 11@22:50
> 
> DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.telegram.org
> DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (2): api.telegram.org
> DEBUG:urllib3.connectionpool:https://api.telegram.org:443 "POST /botDELETE/sendMessage HTTP/1.1" 400 73
> DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
> DEBUG:urllib3.connectionpool:https://api.telegram.org:443 "POST /botDELETE/sendMessage HTTP/1.1" 400 73
> DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
> DEBUG:urllib3.connectionpool:https://api.telegram.org:443 "POST /botDELETE/sendMessage HTTP/1.1" 400 73
> DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
> DEBUG:urllib3.connectionpool:https://api.telegram.org:443 "POST /botDELETE/sendMessage HTTP/1.1" 400 73
> DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
> DEBUG:urllib3.connectionpool:https://api.telegram.org:443 "POST /botDELETE/sendMessage HTTP/1.1" 400 73
> DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
> DEBUG:urllib3.connectionpool:https://api.telegram.org:443 "POST /botDELETE/sendMessage HTTP/1.1" 400 73
> DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
> DEBUG:urllib3.connectionpool:https://api.telegram.org:443 "POST /botDELETE/sendMessage HTTP/1.1" 400 73
> DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
> DEBUG:urllib3.connectionpool:https://api.telegram.org:443 "POST /botDELETE/sendMessage HTTP/1.1" 400 73
> DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
> DEBUG:urllib3.connectionpool:https://api.telegram.org:443 "POST /botDELETE/sendMessage HTTP/1.1" 400 73
> DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=0, status=None)
> DEBUG:urllib3.connectionpool:https://api.telegram.org:443 "POST /botDELETE/sendMessage HTTP/1.1" 400 73

**Comment by mvrozanti** [comment]
Was appending to wrong log file, my bad.
