### ISSUE TITLE
get_chrome don't work

### ISSUE THREAD

**Issue by badboy051** [mvrozanti/RAT-via-Telegram#35]
`

 (most recent call last):
  File "C:\Python27\lib\site-packages\telepot\__init__.py", line 1158, in collector
    callback(item)
  File "scvhost.py", line 332, in handle
    cursor.execute("SELECT origin_url,username_value,password_value from logins;")
OperationalError: database is locked

`
you can use Radium_keylogger for this one

**Comment by mvrozanti** [comment]
`OperationalError: database is locked`

You found your error. Something is accessing the sqlite database file, is it not?
