### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Patrickology** [mvrozanti/RAT-via-Telegram#4]
![keyerror](https://cloud.githubusercontent.com/assets/28252390/26084188/9a06fc2e-39da-11e7-9d46-b597e43eeeff.png)

Perhaps I did something wrong setting it all up with Python and stuff but this is the error I got..

**Comment by mvrozanti** [comment]
`os.environ` is a dictionary. I set that up so we don't have to actually paste our token into the program. I accidentally pushed it into the repo once and had to deauthorize and so on...

What you want is this (supposing you want the token in your code...):
`token = '380089595:AAHuaAQaGt...'`

Tell me how that works out for ya

**Comment by Patrickology** [comment]
Thanks bro, that helped resolving the KeyError on the token.
However a new KeyError popped up:

![image](https://cloud.githubusercontent.com/assets/28252390/26174553/0c93948e-3b50-11e7-9e06-7712d6cae075.png)

Sorry to bother again but I really would like to see this thing at work lol

**Comment by mvrozanti** [comment]
Same thing. Are you familiar with Python? I suggest you reading up on dictionaries and how they work. Anyway:

`SETX TELEGRAM_CHAT_ID <your_chat_id>`

**Comment by Patrickology** [comment]
Yeah that worked however what I did is enter chat ID in the line known_ids = and the next line I removed. Not sure if I was supposed to but there you go.

No I'm not familiar with python honestly. I came across the script though some website, can't even remember.

Anyway after running the python RATAttack.py command the bot in Telegram suddenly said PCJWDSKTP: I'm up.

Then I ran the command to compile that .bat file, a whole bunch of stuff happened and it produced a RATattack.exe file in the dist folder.

Think I'm getting close to running this gem now.

If you have time and want to help me out a bit more on what to do next, please hit me up on Telegram @AssasNin would really appreciate it.

Best regards,

Patrick.
