### ISSUE TITLE
KeyError: 'RAT_TOKEN'

### ISSUE THREAD

**Issue by Ubop0202** [mvrozanti/RAT-via-Telegram#41]
Hi guys, need a help!
When i run python RATAttack.py, i have this errors: 

> >python RATAttack.py
> Traceback (most recent call last):
>   File "RATAttack.py", line 35, in <module>
>     token = os.environ['RAT_TOKEN'] #you can set your environment variable as well
>   File "C:\Python27\lib\os.py", line 425, in __getitem__
>     return self.data[key.upper()]
> KeyError: 'RAT_TOKEN'

so my telegram bot does not respond :( sos, pls help

**Comment by PulkitSingh256** [comment]
This issue is already solved

**Comment by Ubop0202** [comment]
tnx, for ur response. could u give a link for solution? tnx in advance

**Comment by Ubop0202** [comment]
#token = os.environ['RAT_TOKEN']

Comment # helped me

**Comment by Ubop0202** [comment]
and another question sir, for the chat id, is it possible to use my own id, not group id?

**Comment by mvrozanti** [comment]
@Ubop0202 I don't understand the question. You can't _choose_ an ID, it's assigned to you from Telegram.
