### ISSUE TITLE
Run Time Error

### ISSUE THREAD

**Issue by DarkNoobHunter** [mvrozanti/RAT-via-Telegram#46]
File "RATAttack.py", line 35, in <module>
    token = os.environ['RAT_TOKEN']                                             # you can set your environment variable as well
  File "C:\Python27\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'RAT_TOKEN'

**Comment by mvrozanti** [comment]
Check #39 and report back if it worked
