### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by DarkNoobHunter** [mvrozanti/RAT-via-Telegram#47]
C:\Users\hamza\Pictures\RAT-via-Telegram-master\RAT-via-Telegram-master>python RATAttack.py
Traceback (most recent call last):
  File "RATAttack.py", line 35, in <module>
    token = os.environ['RAT_TOKEN']                                             # you can set your environment variable as well
  File "C:\Python27\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'RAT_TOKEN'

C:\Users\hamza\Pictures\RAT-via-Telegram-master\RAT-via-Telegram-master>python RATAttack.py
Traceback (most recent call last):
  File "RATAttack.py", line 35, in <module>
    token = os.environ['RAT_TOKEN']                                             # you can set your environment variable as well
  File "C:\Python27\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'RAT_TOKEN'

**Comment by mvrozanti** [comment]
#39 probably fixes it
I've been getting a lot of issues reports on this
Report back so we know it worked
