### ISSUE TITLE
After setting chat_id the bot stops to response

### ISSUE THREAD

**Issue by Dagdelo** [mvrozanti/RAT-via-Telegram#48]
I get my chat_id, put in knows_ids list and after that the bots says: "DESKTOP-01: I'm up." DESKTOP-01 is my pc that are running the server, but i can't send nothing for him... What I'm doing wrong?

**Comment by mvrozanti** [comment]
> i can't send nothing for him

How so? I'm gonna need more than that

**Comment by Dagdelo** [comment]
![image](https://user-images.githubusercontent.com/10082704/46909497-c7e30780-cf09-11e8-8b67-89ef9bc97e94.png)
See: The bot says: I'm up! But when I send a message from the same computer as the server, or from the phone him don't respond.

**Comment by mvrozanti** [comment]
That is fairly strange. It outputs `<Divide>PC`.

**Comment by Dagdelo** [comment]
> That is fairly strange. It outputs `<Divide>PC`.

It's because I typed the '/pc' on Telegram window.
É porque eu escrevi '/pc' na janela do Telegram.

**Comment by mvrozanti** [comment]
I must ask, have you double-checked that chat_id is *really* your `chat_id`?

**Comment by Dagdelo** [comment]
Yeah. I double checked with @my_id_bot he answered the same id.

**Comment by mvrozanti** [comment]
I rarely work on this project anymore but I'd try and fiddle with the known_ids list if I were you

**Comment by Dagdelo** [comment]
The problem was that I had put the id as int not as string. After put as string worked as expected.

**Comment by mvrozanti** [comment]
Good idea, happy you solved it. May I close this issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
