### ISSUE TITLE
pyaudio error

### ISSUE THREAD

**Issue by Suburbanno** [mvrozanti/RAT-via-Telegram#55]
C:\Users\Vinicius\Desktop\RAT>python RATAttack.py
Traceback (most recent call last):
  File "RATAttack.py", line 26, in <module>
    import pyaudio, wave                                                                        # /hear
ModuleNotFoundError: No module named 'pyaudio'

**Comment by dudeisbrendan03** [comment]
You need to install pyAudio and pyHook. There are two wheel files for each one (32 and 64bit).

To install a wheel just do `pip install FILE_NAME`

**Comment by Suburbanno** [comment]
C:\WINDOWS\system32>pip install pyaudio
Collecting pyaudio
  Downloading https://files.pythonhosted.org/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz
Building wheels for collected packages: pyaudio
  Running setup.py bdist_wheel for pyaudio ... error
  Complete output from command c:\users\vinicius\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Vinicius\\AppData\\Local\\Temp\\pip-install-xcm5me62\\pyaudio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Vinicius\AppData\Local\Temp\pip-wheel-411brlg1 --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  copying src\pyaudio.py -> build\lib.win-amd64-3.7
  running build_ext
  building '_portaudio' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\src
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DMS_WIN64=1 -Ic:\users\vinicius\appdata\local\programs\python\python37\include -Ic:\users\vinicius\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /Tcsrc/_portaudiomodule.c /Fobuild\temp.win-amd64-3.7\Release\src/_portaudiomodule.obj
  _portaudiomodule.c
  c:\users\vinicius\appdata\local\programs\python\python37\include\pyconfig.h(117): warning C4005: 'MS_WIN64': macro redefinition
  c:\users\vinicius\appdata\local\programs\python\python37\include\pyconfig.h(117): note: command-line arguments:  see previous definition of 'MS_WIN64'
  src/_portaudiomodule.c(29): fatal error C1083: Cannot open include file: 'portaudio.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for pyaudio
  Running setup.py clean for pyaudio
Failed to build pyaudio
Installing collected packages: pyaudio
  Running setup.py install for pyaudio ... error
    Complete output from command c:\users\vinicius\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Vinicius\\AppData\\Local\\Temp\\pip-install-xcm5me62\\pyaudio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Vinicius\AppData\Local\Temp\pip-record-w47ey69j\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying src\pyaudio.py -> build\lib.win-amd64-3.7
    running build_ext
    building '_portaudio' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DMS_WIN64=1 -Ic:\users\vinicius\appdata\local\programs\python\python37\include -Ic:\users\vinicius\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /Tcsrc/_portaudiomodule.c /Fobuild\temp.win-amd64-3.7\Release\src/_portaudiomodule.obj
    _portaudiomodule.c
    c:\users\vinicius\appdata\local\programs\python\python37\include\pyconfig.h(117): warning C4005: 'MS_WIN64': macro redefinition
    c:\users\vinicius\appdata\local\programs\python\python37\include\pyconfig.h(117): note: command-line arguments:  see previous definition of 'MS_WIN64'
    src/_portaudiomodule.c(29): fatal error C1083: Cannot open include file: 'portaudio.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\vinicius\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Vinicius\\AppData\\Local\\Temp\\pip-install-xcm5me62\\pyaudio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Vinicius\AppData\Local\Temp\pip-record-w47ey69j\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Vinicius\AppData\Local\Temp\pip-install-xcm5me62\pyaudio\

**Comment by dudeisbrendan03** [comment]
No, we have a file in the repo.

**Comment by dudeisbrendan03** [comment]
Do `pip install PyAudio-0.2.11-cp37-cp37m-win_amd64.whl`

**Comment by Suburbanno** [comment]
working now, thanks guy

**Comment by dudeisbrendan03** [comment]
Your welcome guy

**Comment by mvrozanti** [comment]
@dudeisbrendan03 I want to get rid of these wheels. And the UPX binary. I want to clean up a few things. Why aren't we installing pyHook and pyAudio with `pip` again?

**Comment by dudeisbrendan03** [comment]
Last time I was working on this you couldn't install it with pip as it wasn't on Pypi
