### ISSUE TITLE
Print Tofile

### ISSUE THREAD

**Issue by RussianKKK** [mvrozanti/RAT-via-Telegram#58]
File "RAT_Attack.py", line 135
    print tofile
               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(tofile)?

Help?

**Comment by mvrozanti** [comment]
Post `python -V`

**Comment by RussianKKK** [comment]
Python 3.7.1

**Comment by mvrozanti** [comment]
There is no such line in `RATAttack.py` file. I'm not sure how you are getting this. I'd advise to clone the original repository, making minimal required changes and try running that.
