### ISSUE TITLE
Cant Seem to make the EXE work

### ISSUE THREAD

**Issue by dhammysoft** [mvrozanti/RAT-via-Telegram#59]
@mvrozanti i have updated my python done all the necessary module download , when i start the python RATAttack on cmd it does work but when i do compile.bat and i try running the .EXE its throwing error ..VCRUNTIME140.dll is either not to designed to run on windows or Contains an error

**Comment by mvrozanti** [comment]
Can you tell me what UPX version you are using? @dudeisbrendan03 has dealt with this problem before

**Comment by dhammysoft** [comment]
please how do i check  UPX version

**Comment by dudeisbrendan03** [comment]
Hey'o. Sorry I've been inactive, working through a load of school and business stuff at the minute

**Comment by dudeisbrendan03** [comment]
Have you tried reinstalling visual studio runtime? Do you have it installed?

**Comment by dhammysoft** [comment]
thank you for coming through @dudeisbrendan03 yes i have uninstalled and re installed the latest one from microsoft official website

**Comment by dhammysoft** [comment]
![capture](https://user-images.githubusercontent.com/29376096/49332451-5d675300-f5ad-11e8-9943-f8a557eefbd4.JPG)
 

this what comes up at the end when i do "pip install -r requirements.txt"

**Comment by dudeisbrendan03** [comment]
you don't have vcc. Download it

**Comment by dudeisbrendan03** [comment]
Get VCC 14: [here](https://www.techspot.com/downloads/6776-visual-c-redistributable-package.html)

**Comment by dhammysoft** [comment]
Still thesame thing @dudeisbrendan03  microsoft visual C++ 14 still required.. what am i getting wrong

**Comment by dudeisbrendan03** [comment]
uninstall all your VCPP versions and just install 14, then go ahead and install the rest. BUT **BEFORE YOU DO THAT** make sure you restarted your PC after installing VCPP 14.

**Comment by mvrozanti** [comment]
https://stackoverflow.com/questions/48541801/microsoft-visual-c-14-0-is-required-get-it-with-microsoft-visual-c-build-t

**Comment by mvrozanti** [comment]
I would advise very much **against** downloading any executable with from a less than reputable source. I never heard about "techspot" before in my life.

**Comment by dudeisbrendan03** [comment]
Massive tech news site?

**Comment by dudeisbrendan03** [comment]
https://techspot.com/

**Comment by mvrozanti** [comment]
![image](https://user-images.githubusercontent.com/11381662/49335372-61a66700-f5d3-11e8-96ee-386a3250c762.png)
It's HTTPS certification isn't even valid.

**Comment by dudeisbrendan03** [comment]
Valid for me

**Comment by dudeisbrendan03** [comment]
![Img](https://i.imgur.com/S3Rd40Q.png)

Not sure what your problem with the site is

**Comment by mvrozanti** [comment]
@dhammysoft please report back when it's working so we can close this.

**Comment by dudeisbrendan03** [comment]
You need VCPP 14, you can download it through the visual studio installer but expect to be using a few gigs instead of a few hundred mbs.

**Comment by dhammysoft** [comment]
its not working yet definitely it has to do with my microsoft redistributable cause i tried on other system and it worked perfectly. i'm suggesting i reload my OS and reinstall the microsoft vc++

**Comment by dudeisbrendan03** [comment]
What build and version of Windows are both the machines if you don't mind me asking?

**Comment by dhammysoft** [comment]
Sorry it took me awhile to reply @dudeisbrendan03.. the machine giving the error is a windows8.1 64 bit  machine

**Comment by dudeisbrendan03** [comment]
And the one it works on?

**Comment by dhammysoft** [comment]
Windows 7 64bit

**Comment by mvrozanti** [comment]
@dhammysoft have you managed to get it working?
