### ISSUE TITLE
Cant run the RATAttack.exe on Windows server 2012

### ISSUE THREAD

**Issue by insecureboy** [mvrozanti/RAT-via-Telegram#63]
just trying on my windows 2012 server and it cant run. do i need install the requirements on the client pc?

log on window:
C:\Users\myself\AppData\Local\Temp2\_MEI23882\VCRRUNTIME140.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0x000007b.

log on cmd:
C:\Users\myself\Desktop>C:\Users\myself\Desktop\RATAttack.exe
Error loading Python DLL 'C:\Users\myself\AppData\Local\Temp\2\_MEI23882\python
36.dll'.
No error messages generated.
FormatMessageW: The parameter is incorrect.
LoadLibrary: PyInstaller: FormatMessageW failed.

**Comment by mvrozanti** [comment]
Does `C:\Users\myself\AppData\Local\Temp2_MEI23882\VCRRUNTIME140.dll` exist?

Looks like you're missing the right version for VCRRUNTIME. #59 and #42 might give some insight on what to do next.

**Comment by DoggeXL** [comment]
I have the exact same problem on windows 10. I've installed the Visual studio c++ 2015 package along with  some other ones, got the same error on another distribution of windows 10.

**Comment by mvrozanti** [comment]
I don't have a Win10 copy at the moment so I'm not sure how to reproduce this. Have you checked if `VCRRUNTIME140.dll` exists?

**Comment by DoggeXL** [comment]
Yes i have

Den tor 14 feb. 2019 23:26 skrev Marcelo <notifications@github.com>:

**Comment by normaliok** [comment]
So, mvrozanti, how can we fix this problem? Is there a workaround?

**Comment by mvrozanti** [comment]
sadly, until someone with your OS specs shows up, no. I'm open to any contributions though.

**Comment by Trustdee** [comment]
**Here is how i fixed mine** 

    Turn windows features on or off
    Skip the roles screen and directly go to Feature screen
    Select "Desktop Experience" under "User Interfaces and Infrastructure"

After this all required dll of opencv would be available.

**Comment by mvrozanti** [comment]
@Trustdee thanks for the tip. Have you tested if this works for you @normaliok?
