### ISSUE TITLE
master branch protection

### ISSUE THREAD

**Issue by dudeisbrendan03** [mvrozanti/RAT-via-Telegram#69]
Can we enable branch protection on master w/
- Must pass tests
- Must have 2 approving PR reviews inc. the PR owner.

If you're ok with that can I leave a notice on the README (that will be removed on the next PR) before you enable it?

**Comment by mvrozanti** [comment]
Sounds great

Do *I* need to enable it? How can I do so?

**Comment by dudeisbrendan03** [comment]
Only maintainers/owners can do it.

[Head over here (settings --> branches)](https://github.com/mvrozanti/RAT-via-Telegram/settings/branches) then hit `Add rule` and add the following checks:

- Require pull request reviews before merging:
_______________
- Require 2 approvals
- Require review from code owners
_______________
- Require status checks to pass before merging
- Include administrators

Let me go ahead and update the README

**Comment by dudeisbrendan03** [comment]
All good! Branch protection just needs to be enabled now

**Comment by mvrozanti** [comment]
it's done

**Comment by dudeisbrendan03** [comment]
Nice, thanks!
