### ISSUE TITLE
Setup Requirement  Error 

### ISSUE THREAD

**Issue by Trustdee** [mvrozanti/RAT-via-Telegram#70]
You are probably running a processor like ARM. This isn't supported due to the lack of dependencies supporting ARM.
Traceback (most recent call last):
  File "setup_rat.py", line 15, in <module>
    s('pip install '+fileA);s('pip install '+fileB)
NameError: name 'fileA' is not defined

**Comment by mvrozanti** [comment]
Yeah, ARM is not supported
