### ISSUE TITLE
While sending cmd : pip install -r requirements.txt

### ISSUE THREAD

**Issue by MAHDI00032** [mvrozanti/RAT-via-Telegram#79]
This is my commend prompt :C:\Users\rayan partov\Desktop\RAT-via-Telegram-master>pip2 install -r requirements.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting telepot
  Using cached telepot-12.7.tar.gz (73 kB)
Collecting requests
  Using cached requests-2.22.0-py2.py3-none-any.whl (57 kB)
Collecting image
  Using cached image-1.5.28.tar.gz (15 kB)
Collecting winshell
  Using cached winshell-0.6.zip (10 kB)
Collecting tendo
  Using cached tendo-0.2.15-py2.py3-none-any.whl (23 kB)
Collecting pypiwin32
  Using cached pypiwin32-223.tar.gz (622 bytes)
Collecting pyinstaller
  Using cached PyInstaller-3.6.tar.gz (3.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting psutil
  Using cached psutil-5.6.7-cp27-none-win_amd64.whl (231 kB)
Collecting pillow
  Using cached Pillow-6.2.2-cp27-cp27m-win_amd64.whl (1.9 MB)
Collecting opencv-python
  Using cached opencv_python-4.1.2.30-cp27-cp27m-win_amd64.whl (33.0 MB)
ERROR: Could not find a version that satisfies the requirement console-tools (from -r requirements.txt (line 11)) (from versions: none)
ERROR: No matching distribution found for console-tools (from -r requirements.txt (line 11))

**Comment by mvrozanti** [comment]
Switch to pip3
