### ISSUE TITLE
Script shows error message when no internet connection on startup

### ISSUE THREAD

**Issue by LearnerZone** [mvrozanti/RAT-via-Telegram#8]
On computer startup/first-run if there is no internet connection a script execution failure error message-box is shown, this blows-away the RAT's stealth capability. 

We should check the internet connectivity on startup and either keep looping until a connection is available or exit the script to avoid any display f message-box. Something like the code below (untested) should fix this:

```
#check internet connectivity and keep looping
while True:
	try:
		socket.create_connection(("www.google.com", 80))
		break
	except socket.error:
		time.sleep(3);

```

**Comment by Patrickology** [comment]
I 'infected'my laptop last Friday for testing purposes and today I wanted to play with a again a bit more so I fired up the laptop and got this error message:

![image](https://cloud.githubusercontent.com/assets/28252390/26307853/f785b69e-3ef6-11e7-84ad-a39427f7a52c.png)

**Comment by mvrozanti** [comment]
New version out. Can you check if it covers all our needs?
