### ISSUE TITLE
Compile not working

### ISSUE THREAD

**Issue by theperfectcoder** [mvrozanti/RAT-via-Telegram#83]
Requirement already satisfied: numpy>=1.17.3 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from opencv-python->-r requirements.txt (line 10)) (1.19.0)
Requirement already satisfied: colorama in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from console-tools->-r requirements.txt (line 11)) (0.4.3)
Requirement already satisfied: termcolor in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from console-tools->-r requirements.txt (line 11)) (1.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from aiohttp>=3.0.0->telepot->-r requirements.txt (line 1)) (1.4.2)
Requirement already satisfied: attrs>=17.3.0 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from aiohttp>=3.0.0->telepot->-r requirements.txt (line 1)) (19.3.0)
Requirement already satisfied: multidict<5.0,>=4.5 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from aiohttp>=3.0.0->telepot->-r requirements.txt (line 1)) (4.7.6)
Requirement already satisfied: async-timeout<4.0,>=3.0 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from aiohttp>=3.0.0->telepot->-r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: asgiref~=3.2 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from django->image->-r requirements.txt (line 3)) (3.2.10)
Requirement already satisfied: sqlparse>=0.2.2 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from django->image->-r requirements.txt (line 3)) (0.3.1)
Requirement already satisfied: pytz in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from django->image->-r requirements.txt (line 3)) (2020.1)
Requirement already satisfied: future in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from pefile>=2017.8.1->pyinstaller->-r requirements.txt (line 7)) (0.18.2)
Traceback (most recent call last):
  File "compile.py", line 75, in <module>
    download_dependencies()
  File "compile.py", line 59, in download_dependencies
    download_and_install_lfd_uci_wheel('pyAudio')
  File "compile.py", line 45, in download_and_install_lfd_uci_wheel
    wheel_filename  = m.group(2).replace('&#8209;', '-').replace('&#46;', '.')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by mvrozanti** [comment]
Check out #82
