### ISSUE TITLE
can not compile

### ISSUE THREAD

**Issue by theperfectcoder** [mvrozanti/RAT-via-Telegram#84]
Now going to install dependencies and compile the rat, make sure you have prepped RATAttack.py beforehand

Press ENTER to resume
Requirement already satisfied: telepot in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from -r requirements.txt (line 1)) (12.7)
Requirement already satisfied: requests in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from -r requirements.txt (line 2)) (2.24.0)
Requirement already satisfied: image in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from -r requirements.txt (line 3)) (1.5.32)
Requirement already satisfied: winshell in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from -r requirements.txt (line 4)) (0.6)
Requirement already satisfied: tendo in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from -r requirements.txt (line 5)) (0.2.15)
Requirement already satisfied: pypiwin32 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from -r requirements.txt (line 6)) (223)
Requirement already satisfied: pyinstaller in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from -r requirements.txt (line 7)) (3.6)
Requirement already satisfied: psutil in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from -r requirements.txt (line 8)) (5.7.2)
Requirement already satisfied: pillow in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from -r requirements.txt (line 9)) (7.2.0)
Requirement already satisfied: opencv-python in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from -r requirements.txt (line 10)) (4.3.0.36)
Requirement already satisfied: console-tools in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from -r requirements.txt (line 11)) (0.2.1)
Requirement already satisfied: urllib3>=1.9.1 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from telepot->-r requirements.txt (line 1)) (1.25.9)
Requirement already satisfied: aiohttp>=3.0.0 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from telepot->-r requirements.txt (line 1)) (3.6.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from requests->-r requirements.txt (line 2)) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from requests->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from requests->-r requirements.txt (line 2)) (2.10)
Requirement already satisfied: django in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from image->-r requirements.txt (line 3)) (3.0.8)
Requirement already satisfied: six in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from image->-r requirements.txt (line 3)) (1.15.0)
Requirement already satisfied: setuptools in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from tendo->-r requirements.txt (line 5)) (47.1.0)
Requirement already satisfied: pip in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from tendo->-r requirements.txt (line 5)) (20.1.1)
Requirement already satisfied: pbr in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from tendo->-r requirements.txt (line 5)) (5.4.5)
Requirement already satisfied: pywin32>=223 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from pypiwin32->-r requirements.txt (line 6)) (228)
Requirement already satisfied: altgraph in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from pyinstaller->-r requirements.txt (line 7)) (0.17)
Requirement already satisfied: pefile>=2017.8.1 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from pyinstaller->-r requirements.txt (line 7)) (2019.4.18)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from pyinstaller->-r requirements.txt (line 7)) (0.2.0)
Requirement already satisfied: numpy>=1.17.3 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from opencv-python->-r requirements.txt (line 10)) (1.19.0)
Requirement already satisfied: colorama in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from console-tools->-r requirements.txt (line 11)) (0.4.3)
Requirement already satisfied: termcolor in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from console-tools->-r requirements.txt (line 11)) (1.1.0)
Requirement already satisfied: multidict<5.0,>=4.5 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from aiohttp>=3.0.0->telepot->-r requirements.txt (line 1)) (4.7.6)
Requirement already satisfied: attrs>=17.3.0 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from aiohttp>=3.0.0->telepot->-r requirements.txt (line 1)) (19.3.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from aiohttp>=3.0.0->telepot->-r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from aiohttp>=3.0.0->telepot->-r requirements.txt (line 1)) (1.4.2)
Requirement already satisfied: asgiref~=3.2 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from django->image->-r requirements.txt (line 3)) (3.2.10)
Requirement already satisfied: pytz in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from django->image->-r requirements.txt (line 3)) (2020.1)
Requirement already satisfied: sqlparse>=0.2.2 in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from django->image->-r requirements.txt (line 3)) (0.3.1)
Requirement already satisfied: future in c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages (from pefile>=2017.8.1->pyinstaller->-r requirements.txt (line 7)) (0.18.2)
'upx' is not recognized as an internal or external command,
operable program or batch file.

Did the install run correctly?

Press ENTER to build
133 INFO: PyInstaller: 3.6
133 INFO: Python: 3.8.4
138 INFO: Platform: Windows-10-10.0.18362-SP0
146 INFO: wrote C:\Users\sergr\Downloads\RAT-via-Telegram\RATAttack.spec
147 INFO: UPX is not available.
148 INFO: Removing temporary files and cleaning cache in C:\Users\sergr\AppData\Roaming\pyinstaller
203 INFO: Extending PYTHONPATH with paths
['C:\\Users\\sergr\\Downloads\\RAT-via-Telegram',
 'C:\\Users\\sergr\\Downloads\\RAT-via-Telegram']
204 INFO: checking Analysis
208 INFO: Building Analysis because Analysis-00.toc is non existent
213 INFO: Initializing module dependency graph...
216 INFO: Caching module graph hooks...
226 INFO: Analyzing base_library.zip ...
3170 INFO: Processing pre-find module path hook   distutils
3171 INFO: distutils: retargeting to non-venv dir 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\\lib'
5072 INFO: Caching module dependency graph...
5185 INFO: running Analysis Analysis-00.toc
5192 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\sergr\downloads\rat-via-telegram\venv\scripts\python.exe
5211 INFO: Analyzing C:\Users\sergr\Downloads\RAT-via-Telegram\RATAttack.py
6802 INFO: Processing pre-find module path hook   site
6804 INFO: site: retargeting to fake-dir 'c:\\users\\sergr\\downloads\\rat-via-telegram\\venv\\lib\\site-packages\\PyInstaller\\fake-modules'
8138 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
11245 INFO: Processing pre-safe import module hook   win32com
12126 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
13740 INFO: Processing module hooks...
13740 INFO: Loading module hook "hook-certifi.py"...
13747 INFO: Loading module hook "hook-cv2.py"...
13750 INFO: Loading module hook "hook-distutils.py"...
13774 INFO: Loading module hook "hook-encodings.py"...
13948 INFO: Loading module hook "hook-lib2to3.py"...
13969 INFO: Loading module hook "hook-numpy.core.py"...
14143 INFO: Loading module hook "hook-numpy.py"...
14146 INFO: Loading module hook "hook-PIL.Image.py"...
14688 INFO: Loading module hook "hook-PIL.py"...
14691 INFO: Excluding import 'PyQt5'
14694 INFO:   Removing import of PyQt5 from module PIL.ImageQt
14696 INFO: Excluding import 'tkinter'
14702 INFO:   Removing import of tkinter from module PIL.ImageTk
14704 INFO: Import to be excluded not found: 'PySide'
14704 INFO: Import to be excluded not found: 'PyQt4'
14708 INFO: Import to be excluded not found: 'FixTk'
14710 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
14717 INFO: Import to be excluded not found: 'FixTk'
14717 INFO: Excluding import 'tkinter'
14721 INFO: Loading module hook "hook-pkg_resources.py"...
15333 INFO: Excluding import '__main__'
15334 INFO:   Removing import of __main__ from module pkg_resources
15334 INFO: Loading module hook "hook-pydoc.py"...
15339 INFO: Loading module hook "hook-pythoncom.py"...
15679 INFO: Loading module hook "hook-pywintypes.py"...
15999 INFO: Loading module hook "hook-setuptools.py"...
16626 INFO: Loading module hook "hook-sqlite3.py"...
16793 INFO: Loading module hook "hook-sysconfig.py"...
16797 INFO: Loading module hook "hook-win32com.py"...
16851 INFO: Loading module hook "hook-xml.dom.domreg.py"...
16852 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
16853 INFO: Loading module hook "hook-xml.py"...
16857 INFO: Loading module hook "hook-_tkinter.py"...
16880 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\_tkinter.pyd
17153 INFO: checking Tree
17153 INFO: Building Tree because Tree-00.toc is non existent
17155 INFO: Building Tree Tree-00.toc
17270 INFO: checking Tree
17270 INFO: Building Tree because Tree-01.toc is non existent
17271 INFO: Building Tree Tree-01.toc
17332 INFO: Looking for ctypes DLLs
17380 INFO: Analyzing run-time hooks ...
17387 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
17391 INFO: Including run-time hook 'pyi_rth_pkgres.py'
17394 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
17396 INFO: Including run-time hook 'pyi_rth_certifi.py'
17427 INFO: Looking for dynamic libraries
17455 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\pywin32_system32\pywintypes38.dll
17573 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\pywin32_system32\pythoncom38.dll
17600 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\_ssl.pyd
17619 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\win32\win32trace.pyd
17636 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\_multiprocessing.pyd
17648 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\_queue.pyd
17666 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\_hashlib.pyd
17684 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\select.pyd
17698 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\_overlapped.pyd
17707 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\_asyncio.pyd
17736 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\unicodedata.pyd
17756 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\_lzma.pyd
17782 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\_bz2.pyd
17801 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\pyexpat.pyd
17824 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\_decimal.pyd
17837 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\win32\_win32sysloader.pyd
17872 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\Pythonwin\win32ui.pyd
17904 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\win32\win32api.pyd
17935 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\win32\win32wnet.pyd
17954 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\win32comext\shell\shell.pyd
17973 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\winsound.pyd
17992 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\numpy\core\_multiarray_tests.cp38-win_amd64.pyd
18017 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\numpy\core\_multiarray_umath.cp38-win_amd64.pyd
18040 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\win32\win32pdh.pyd
18060 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\numpy\linalg\lapack_lite.cp38-win_amd64.pyd
18072 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\numpy\random\mtrand.cp38-win_amd64.pyd
18093 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\numpy\random\_sfc64.cp38-win_amd64.pyd
18106 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\numpy\random\_philox.cp38-win_amd64.pyd
18120 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\numpy\random\_pcg64.cp38-win_amd64.pyd
18141 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\numpy\random\_mt19937.cp38-win_amd64.pyd
18150 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\numpy\random\bit_generator.cp38-win_amd64.pyd
18179 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\numpy\random\_generator.cp38-win_amd64.pyd
18197 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\numpy\random\_bounded_integers.cp38-win_amd64.pyd
18205 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\numpy\random\_common.cp38-win_amd64.pyd
18233 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\numpy\fft\_pocketfft_internal.cp38-win_amd64.pyd
18255 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\numpy\linalg\_umath_linalg.cp38-win_amd64.pyd
18285 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\_ctypes.pyd
18354 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\cv2\cv2.cp38-win_amd64.pyd
18385 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\_socket.pyd
18411 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\win32\win32crypt.pyd
18436 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\_sqlite3.pyd
18455 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\win32\win32clipboard.pyd
18484 WARNING: lib not found: python38.dll dependency of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\DLLs\_elementtree.pyd
18515 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\psutil\_psutil_windows.cp38-win_amd64.pyd
18553 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\PIL\_imagingtk.cp38-win_amd64.pyd
18583 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\PIL\_webp.cp38-win_amd64.pyd
18612 WARNING: lib not found: python38.dll dependency of c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\PIL\_imaging.cp38-win_amd64.pyd
18786 INFO: Looking for eggs
18786 INFO: Python library not in binary dependencies. Doing additional searching...
18791 INFO: Using Python library
18792 INFO: Found binding redirects:
[]
18804 INFO: Warnings written to C:\Users\sergr\Downloads\RAT-via-Telegram\build\RATAttack\warn-RATAttack.txt
18925 INFO: Graph cross-reference written to C:\Users\sergr\Downloads\RAT-via-Telegram\build\RATAttack\xref-RATAttack.html
18954 INFO: checking PYZ
18954 INFO: Building PYZ because PYZ-00.toc is non existent
18956 INFO: Building PYZ (ZlibArchive) C:\Users\sergr\Downloads\RAT-via-Telegram\build\RATAttack\PYZ-00.pyz
20286 INFO: Building PYZ (ZlibArchive) C:\Users\sergr\Downloads\RAT-via-Telegram\build\RATAttack\PYZ-00.pyz completed successfully.
20316 INFO: checking PKG
20317 INFO: Building PKG because PKG-00.toc is non existent
20318 INFO: Building PKG (CArchive) PKG-00.pkg
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sergr\Downloads\RAT-via-Telegram\venv\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "C:\Users\sergr\Downloads\RAT-via-Telegram\RATAttack.spec", line 20, in <module>
    exe = EXE(pyz,
  File "c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\PyInstaller\building\api.py", line 433, in __init__
    self.pkg = PKG(self.toc, cdict=kwargs.get('cdict', None),
  File "c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\PyInstaller\building\api.py", line 199, in __init__
    self.__postinit__()
  File "c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\PyInstaller\building\api.py", line 259, in assemble
    fnm = checkCache(fnm, strip=self.strip_binaries,
  File "c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\PyInstaller\building\utils.py", line 220, in checkCache
    digest = cacheDigest(fnm, redirects)
  File "c:\users\sergr\downloads\rat-via-telegram\venv\lib\site-packages\PyInstaller\building\utils.py", line 365, in cacheDigest
    with open(fnm, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by mvrozanti** [comment]
> 'upx' is not recognized as an internal or external command,

Have you read the README?
Relevant instructions:

"Run compile.py. You can also pass --icon=<path/to/icon.ico> to use a custom icon. If you want to use UPX for compression, you can add --upx-dir [upx-3.95-win64 | upx-3.96-win32], depending on your architecture. You can skip this last option if you have UPX in your PATH environment variable."

Make sure you have UPX in PATH.
