### ISSUE TITLE
/play error occurred

### ISSUE THREAD

**Issue by Patrickology** [mvrozanti/RAT-via-Telegram#9]
Hi,

issued the /play command and the browser on the target opens a new tab and it seems like a video is about to play but you only see the play button and nothing else happens.

![image](https://cloud.githubusercontent.com/assets/28252390/26656014/99a9b7e6-465d-11e7-9155-039dd7044a88.png)

**Comment by mvrozanti** [comment]
`/play` without arguments caused the program to try and start the video except there was no video ID so even though YouTube processes that request, it shows nothing as the videoid itself is missing.

`/play` now responds with command format when no argument is given. Thanks for poiting it out.
